fix: AttributeError: 'PurchaseReceiptItem' object has no attribute 'purchase_invoice' (#25902)
* fix: AttributeError: 'PurchaseReceiptItem' object has no attribute 'purchase_invoice'

This error occurs when upgrading from erpnext 13.0.1 to 13.4.0 after typing
bench update --patch --reset

* fix(minor): use .get instead of getattr