fix: reposting error `AttributeError: 'datetime.timedelta' object has no attribute 'replace'`
(cherry picked from commit eeda264eb6b53cf4e463f8de121d9c5b3371faa8)