fix: Change wrong format_date to formatdate
Installing erpnext...
Updating DocTypes for erpnext       : [===                                     ]An error occurred while installing erpnext:
Module import failed for Process Statement Of Accounts (erpnext.accounts.doctype.process_statement_of_accounts.process_statement_of_accounts Error: cannot import name 'format_date' from 'frappe.utils' (/home/erpfrappe/frappe-bench/apps/frappe/frappe/utils/__init__.py))

This is caused by wrong format_date name. The correct name is formatdate. (Author is probably confused with format_datetime)